apiVersion: v1
kind: Service
metadata:
  name: grafana-np
  namespace: monitoring
spec:
  ports:
  - name: service
    port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 31300
  selector:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
  type: NodePort
